### ISSUE TITLE
Toggle Commands

### ISSUE THREAD

**Issue by Wild1145** [Superior-Development/CommandViewer#4]
Due to initial problems with the implementation of commands, I decided to just scrap the idea, however it really does need to be added to give that extra options to the players on the server.

**Comment by Hockeyfan360** [comment]
Toggle all commands, certain commands, could you explain a little more?

**Comment by Wild1145** [comment]
By this I mean the ability to toggle the plugins functionality for said user on and off. So if you are a admin and do not actually want / need to see every command, you can just toggle it off.
