### ISSUE TITLE
Does not work on 1.8.7

### ISSUE THREAD

**Issue by TiTo-418** [Superior-Development/CommandViewer#9]
Logs: http://pastebin.com/VzX5U4aM

**Comment by Wild1145** [comment]
Hello,

This is not an issue with MC Versions specifically, this is an issue with your provider running an older version of Java on the servers. Generally all my plugins are build with Java 8, meaning if your provider runs 7 or earlier, it will break (and that is what this error here is). 

I will look to compile the plugin with Java 7 and publish and update on Spigot for you in the next 24 hours.

**Comment by TiTo-418** [comment]
Thanks!
